import Head from "next/head";
import localFont from "next/font/local";
import Banners from "@/components/home/Banners";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App with Strapi API using Page Router Method</title>
        <meta name="description" content="Generated by Julnar Nabeel" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Banners/>
      </div>
    </>
  );
}
